[package]
name = "backend-core"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = { workspace = true }

[dependencies]
axum = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = "2.0.17"